In [1]:
import tensorflow as tf

2025-09-16 20:57:38.844807: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
dataset = tf.data.Dataset.from_tensor_slices(tf.range(10))

I0000 00:00:1758023863.578858  107763 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 166 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
I0000 00:00:1758023863.611299  107763 cuda_executor.cc:508] failed to allocate 166.31MiB (174391296 bytes) from device: RESOURCE_EXHAUSTED: : CUDA_ERROR_OUT_OF_MEMORY: out of memory


In [9]:
for i in dataset.batch(7):
    print(i)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)


In [12]:
for i in dataset.repeat(2):
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [16]:
for i in dataset.repeat(3).batch(7,drop_remainder=True):
    print(i)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [26]:
dataset_batch = dataset.batch(3, drop_remainder=True)

In [27]:
for i in dataset_batch:
    print(i)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([6 7 8], shape=(3,), dtype=int32)


In [28]:
for i in dataset_batch.map(lambda x:x*2):
    print(i)

tf.Tensor([0 2 4], shape=(3,), dtype=int32)
tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)
tf.Tensor([12 14 16], shape=(3,), dtype=int32)


In [30]:
for i in dataset_batch.map(lambda x:x*2).shuffle(buffer_size=4, seed=42):
    print(i)

tf.Tensor([0 2 4], shape=(3,), dtype=int32)
tf.Tensor([12 14 16], shape=(3,), dtype=int32)
tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)
